"""add executions table

Revision ID: 01a49cc917ee
Revises: 55df0feb4374
Create Date: 2026-03-27 15:06:43.061448
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "01a49cc917ee"
down_revision: str | None = "55df0feb4374"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("messages", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("tool_calls", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("final_response", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executions_agent_id"), "executions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_executions_tenant_id"), "executions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_executions_tenant_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_agent_id"), table_name="executions")
    op.drop_table("executions")
    # ### end Alembic commands ###
